name: zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: (Zig) Build
        run: zig build --summary all -Dtools -Dshared -freference-trace
      - name: (Zig) Test
        run: zig build test -freference-trace